### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Cruyun** [darkglimmer/xueer#2]
- CSS reset不仅仅是body、HTML，像button、a这种也可以的，具体的自己查查

**header**

- 这部分元素的居中应该是`display: inline-block;` `vertical-align: middle;`，抽成一个class复用。不要乱用vertical-align，这样代码看起来很乱。
- 登录注册按钮的子元素`<a>`和谁对齐了？为什么要`display: inline-block;``vertical-align: middle;`

**middle**

- class不要起body这种和标签名相同的，容易引起误会和错误，命名尽量语义化。
- `cousre_1`的用了`vertical-align: bottom;`和`vertical-align: top;`？那到底是怎么样对齐的呢？其实这里的`vertical-align: bottom;`没有生效。
- `add`写的不对，像上面的盒子一样让字居中，不要用设置padding的各个值来居中一行字。
- 评论里面的用户名字和hot没有对齐哦
- `note`里面有三个margin的值，可以用一个margin写，剩余一个值写成0
- span就是行内元素，默认在同一行。不需要另外设置`display: inline-block; vertical-align: top;`的。去查查行内元素、块级元素的区别特点，总结一下。
- 发布评论按钮：button里面的字是默认居中的，不用`text-align: center`，高度为什么不用height而是`line-height: 30px;`？另外，他的布局应该是居中的，不要用margin-left来写居中，这一点在上一个页面已经强调过。

**Comment by darkglimmer** [comment]
https://github.com/darkglimmer/xueer/commit/b10006e223f8a9aa4a920a6bc643af410c1dc8b5
